name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: crdc_precheck
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5
      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]
        options: >-
          --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install -e packages/shared -e packages/rules -e apps/api[dev] -e apps/worker[dev]

      - name: Run Python linters
        run: |
          ruff check .
          black --check .

      - name: Run Python tests
        env:
          DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/crdc_precheck
        run: pytest -q

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Enable Corepack
        run: corepack enable

      - name: Install web dependencies
        run: pnpm install --dir apps/web

      - name: Run web lint and tests
        run: |
          pnpm --dir apps/web lint
          pnpm --dir apps/web test -- --run
